services:
  db:
    image: myuser/pgvector
    container_name: pgvector
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: enjoy666
      POSTGRES_DB: gmail_agent
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/initdb:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-gmail-agent:dev
    container_name: gmail_agent
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - server/.env
    restart: unless-stopped

volumes:
  pgdata:
